#include "Mod.hpp"

std::unordered_map<int, std::string> ModKey::keycodes{
    {VK_LBUTTON, "Left mouse button"},
    {VK_RBUTTON, "Right mouse button"},
    {VK_CANCEL, "Control-break processing"},
    {VK_MBUTTON, "Middle mouse button (three-button mouse)"},
    {VK_XBUTTON1, "X1 mouse button"},
    {VK_XBUTTON2, "X2 mouse button"},
    {VK_BACK, "BACKSPACE key"},
    {VK_TAB, "TAB key"},
    {VK_CLEAR, "CLEAR key"},
    {VK_RETURN, "ENTER key"},
    {VK_SHIFT, "SHIFT key"},
    {VK_CONTROL, "CTRL key"},
    {VK_MENU, "ALT key"},
    {VK_PAUSE, "PAUSE key"},
    {VK_CAPITAL, "CAPS LOCK key"},
    {VK_KANA, "IME Kana mode"},
    {VK_HANGUL, "IME Hangul mode"},
    {VK_IME_ON, "IME On"},
    {VK_JUNJA, "IME Junja mode"},
    {VK_FINAL, "IME final mode"},
    {VK_HANJA, "IME Hanja mode"},
    {VK_KANJI, "IME Kanji mode"},
    {VK_IME_OFF, "IME Off"},
    {VK_ESCAPE, "ESC key"},
    {VK_CONVERT, "IME convert"},
    {VK_NONCONVERT, "IME nonconvert"},
    {VK_ACCEPT, "IME accept"},
    {VK_MODECHANGE, "IME mode change request"},
    {VK_SPACE, "SPACEBAR"},
    {VK_PRIOR, "PAGE UP key"},
    {VK_NEXT, "PAGE DOWN key"},
    {VK_END, "END key"},
    {VK_HOME, "HOME key"},
    {VK_LEFT, "LEFT ARROW key"},
    {VK_UP, "UP ARROW key"},
    {VK_RIGHT, "RIGHT ARROW key"},
    {VK_DOWN, "DOWN ARROW key"},
    {VK_SELECT, "SELECT key"},
    {VK_PRINT, "PRINT key"},
    {VK_EXECUTE, "EXECUTE key"},
    {VK_SNAPSHOT, "PRINT SCREEN key"},
    {VK_INSERT, "INS key"},
    {VK_DELETE, "DEL key"},
    {VK_HELP, "HELP key"},
    {0x30, "0 key"},
    {0x31, "1 key"},
    {0x32, "2 key"},
    {0x33, "3 key"},
    {0x34, "4 key"},
    {0x35, "5 key"},
    {0x36, "6 key"},
    {0x37, "7 key"},
    {0x38, "8 key"},
    {0x39, "9 key"},
    {0x41, "A key"},
    {0x42, "B key"},
    {0x43, "C key"},
    {0x44, "D key"},
    {0x45, "E key"},
    {0x46, "F key"},
    {0x47, "G key"},
    {0x48, "H key"},
    {0x49, "I key"},
    {0x4A, "J key"},
    {0x4B, "K key"},
    {0x4C, "L key"},
    {0x4D, "M key"},
    {0x4E, "N key"},
    {0x4F, "O key"},
    {0x50, "P key"},
    {0x51, "Q key"},
    {0x52, "R key"},
    {0x53, "S key"},
    {0x54, "T key"},
    {0x55, "U key"},
    {0x56, "V key"},
    {0x57, "W key"},
    {0x58, "X key"},
    {0x59, "Y key"},
    {0x5A, "Z key"},
    {VK_LWIN, "Left Windows key (Natural keyboard)"},
    {VK_RWIN, "Right Windows key (Natural keyboard)"},
    {VK_APPS, "Applications key (Natural keyboard)"},
    {VK_SLEEP, "Computer Sleep key"},
    {VK_NUMPAD0, "Numeric keypad 0 key"},
    {VK_NUMPAD1, "Numeric keypad 1 key"},
    {VK_NUMPAD2, "Numeric keypad 2 key"},
    {VK_NUMPAD3, "Numeric keypad 3 key"},
    {VK_NUMPAD4, "Numeric keypad 4 key"},
    {VK_NUMPAD5, "Numeric keypad 5 key"},
    {VK_NUMPAD6, "Numeric keypad 6 key"},
    {VK_NUMPAD7, "Numeric keypad 7 key"},
    {VK_NUMPAD8, "Numeric keypad 8 key"},
    {VK_NUMPAD9, "Numeric keypad 9 key"},
    {VK_MULTIPLY, "Multiply key"},
    {VK_ADD, "Add key"},
    {VK_SEPARATOR, "Separator key"},
    {VK_SUBTRACT, "Subtract key"},
    {VK_DECIMAL, "Decimal key"},
    {VK_DIVIDE, "Divide key"},
    {VK_F1, "F1 key"},
    {VK_F2, "F2 key"},
    {VK_F3, "F3 key"},
    {VK_F4, "F4 key"},
    {VK_F5, "F5 key"},
    {VK_F6, "F6 key"},
    {VK_F7, "F7 key"},
    {VK_F8, "F8 key"},
    {VK_F9, "F9 key"},
    {VK_F10, "F10 key"},
    {VK_F11, "F11 key"},
    {VK_F12, "F12 key"},
    {VK_F13, "F13 key"},
    {VK_F14, "F14 key"},
    {VK_F15, "F15 key"},
    {VK_F16, "F16 key"},
    {VK_F17, "F17 key"},
    {VK_F18, "F18 key"},
    {VK_F19, "F19 key"},
    {VK_F20, "F20 key"},
    {VK_F21, "F21 key"},
    {VK_F22, "F22 key"},
    {VK_F23, "F23 key"},
    {VK_F24, "F24 key"},
    {VK_NUMLOCK, "NUM LOCK key"},
    {VK_SCROLL, "SCROLL LOCK key"},
    {VK_LSHIFT, "Left SHIFT key"},
    {VK_RSHIFT, "Right SHIFT key"},
    {VK_LCONTROL, "Left CONTROL key"},
    {VK_RCONTROL, "Right CONTROL key"},
    {VK_LMENU, "Left ALT key"},
    {VK_RMENU, "Right ALT key"},
    {VK_BROWSER_BACK, "Browser Back key"},
    {VK_BROWSER_FORWARD, "Browser Forward key"},
    {VK_BROWSER_REFRESH, "Browser Refresh key"},
    {VK_BROWSER_STOP, "Browser Stop key"},
    {VK_BROWSER_SEARCH, "Browser Search key"},
    {VK_BROWSER_FAVORITES, "Browser Favorites key"},
    {VK_BROWSER_HOME, "Browser Start and Home key"},
    {VK_VOLUME_MUTE, "Volume Mute key"},
    {VK_VOLUME_DOWN, "Volume Down key"},
    {VK_VOLUME_UP, "Volume Up key"},
    {VK_MEDIA_NEXT_TRACK, "Next Track key"},
    {VK_MEDIA_PREV_TRACK, "Previous Track key"},
    {VK_MEDIA_STOP, "Stop Media key"},
    {VK_LAUNCH_MAIL, "Start Mail key"},
    {VK_LAUNCH_MEDIA_SELECT, "Select Media key"},
    {VK_LAUNCH_APP1, "Start Application 1 key"},
    {VK_LAUNCH_APP2, "Start Application 2 key"},
    {VK_OEM_1, "OEM 1 key (varies by keyboard layout, usually ';:' or ',<')"},
    {VK_OEM_PLUS, "OEM Plus key (usually '+')"},
    {VK_OEM_COMMA, "OEM Comma key (usually ',')"},
    {VK_OEM_MINUS, "OEM Minus key (usually '-')"},
    {VK_OEM_PERIOD, "OEM Period key (usually '.')"},
    {VK_OEM_2, "OEM 2 key"},
    {VK_OEM_3, "OEM 3 key"}, 
    {VK_OEM_4, "OEM 4 key"}, 
    {VK_OEM_5, "OEM 5 key"}, 
    {VK_OEM_6, "OEM 6 key"}, 
    {VK_OEM_7, "OEM 7 key"},
    {VK_OEM_8, "OEM 8 key"},
    {VK_OEM_102, "OEM 102 key (on some European keyboards, '<>' or '|')"},
    {VK_PROCESSKEY, "IME PROCESS key"},
    {VK_PACKET, "Used to pass Unicode characters as keystrokes"},
    {VK_ATTN, "Attn key"},
    {VK_CRSEL, "CrSel key"},
    {VK_EXSEL, "ExSel key"},
    {VK_EREOF, "Erase EOF key"},
    {VK_PLAY, "Play key"},
    {VK_ZOOM, "Zoom key"},
    {VK_NONAME, "Reserved (no name)"},
    {VK_PA1, "PA1 key"},
    {VK_OEM_CLEAR, "OEM Clear key"},
};